### ISSUE TITLE
Install ElasticSearch 8.8.1 on WIndows 11

### ISSUE THREAD

**Issue by AlvinWong7896** [LisaHJung/Part-1-Intro-to-Elasticsearch-and-Kibana#3]
I am new to programming and ElasticSearch. I have received below message when I try to run "curl http://localhost:9200" after installing ElasticSearch 8.8.1:
{"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","ApiKey"]}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","ApiKey"]}},"status":401}

Please advise how I can resolve the issue/ thank you in advance.

**Comment by apms75** [comment]
I faced a similar issue following the tutorial earlier today and I had to force xpack.security.enabled to false in elasticsearch.yml  
Here my elasticsearch.yml and docker-compose.yml files  

**elasticsearch.yml:**  
```
cluster.name: "docker-cluster"
network.host: 0.0.0.0

# Disable security features
xpack.security.enabled: false
```

**docker-compose.yml:**  
```
services:

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    container_name: elastic
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
      node.name: es-node-01
      cluster.name: es-cluster
      ES_JAVA_OPTS: -Xmx512m -Xms512m
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - elastic-data:/usr/share/elasticsearch/data
    networks:
      - elastic-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.1
    container_name: kibana
    depends_on:
      - elastic
    ports:
      - 5601:5601
      - 9600:9600
    environment:
      SERVERNAME: kibana
      ELASTICSEARCH_HOSTS: http://elastic:9200
      ES_JAVA_OPTS: -Xmx512m -Xms512m
    networks:
      - elastic-network

volumes:
  elastic-data:

networks:
  elastic-network:
    driver: bridge
```
